data:
raw_path: "E:/Diabetes-indicators-disease/data"
processed_path: "data/processed"      # optional
pattern: "*.csv"

train:
random_state: 42
test_size: 0.2
cv: 5
model:
n_estimators: [100]
max_depth: [5, 8]


mlflow:
experiment_name: "Diabetes-Indicators"
run_name: "random_forest_run"


preprocess:
numerical_features: ["Age", "BMI", "PhysicalHealth", "MentalHealth", "SleepTime"]
categorical_features: ["Sex", "Race", "Smoking", "AlcoholDrinking", "Stroke", "DiffWalking", "Diabeti_012", "PhysicalActivity", "GenHealth"]