
paths:
  raw_data: "result/diabetes_merged_clean.csv"
  model: "result/model.pkl"
  metrics: "result/metrics.json"

features:
  target: "Diabetes_binary"

training:
  test_size: 0.2
  random_state: 42
  model_type: "random_forest"

model_params:
  n_estimators: 200
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2

